-----------------------------------------------------------
----          Police Rack and Unrack script            ----
----             Made by Tamir112#5345                 ----
----        For more scripts and updates Join:         ----
----              discord.gg/bDPaRDeBKJ                ----
----                                                   ----
-----------------------------------------------------------

----- DO NOT EDIT THIS FILE, EDIT THE Config.lua -----
----- DO NOT EDIT THIS FILE, EDIT THE Config.lua -----
----- DO NOT EDIT THIS FILE, EDIT THE Config.lua -----
----- DO NOT EDIT THIS FILE, EDIT THE Config.lua -----
local doeshaverifle = false
local doeshaveshotguh = false

Citizen.CreateThread(function ()
  while true do
		Citizen.Wait(400)
    local ped = GetPlayerPed(-1)

  if IsPedArmed(ped, 7) and IsPedArmed(ped, 4) then
     test = GetSelectedPedWeapon(ped)
  
 if test == config.weapon1 then
  if doeshaverifle == false then
ShowNotification('~r~You need to unrack your '..config.weapon1name..' to use it')
RemoveWeaponFromPed(ped , config.weapon1)

  end
end
end
end
end)


Citizen.CreateThread(function ()
  while true do
    local ped = GetPlayerPed(-1)

		Citizen.Wait(400)
  if IsPedArmed(ped, 7) and IsPedArmed(ped, 4) then
     gun = GetSelectedPedWeapon(ped)
  
 if gun == config.weapon2 then
  if doeshaveshotguh == false then
ShowNotification('~r~You need to unrack your beanbag to use it')
RemoveWeaponFromPed(ped , config.weapon2)

 end
end
end
end
end)







RegisterCommand('unrack', function ()

  local ped = GetPlayerPed(-1)
  if IsPedInAnyVehicle(ped, true) then
    local car = GetVehiclePedIsIn(ped, false)
    local t = GetVehicleClass(car)
  if t == 18 then
  if doeshaverifle == false then
      
      ExecuteCommand('me unracks '..config.weapon1name..'')
      ShowNotification('~g~'..config.weapon1name..' unracked')

      doeshaverifle = true
      GiveWeaponToPed(GetPlayerPed(-1), config.weapon1, 1000, false) 
   
  else do
    ShowNotification('~r~You already have a '..config.weapon1name..' on you')
  end
end
else do
  ShowNotification("~r~ You are not in a vehicle")

end
  end
else do ShowNotification("~r~This is not a police car")  end


end
end)

RegisterCommand('rack', function ()

  local ped = GetPlayerPed(-1)
  if IsPedInAnyVehicle(ped, true) then
    local car = GetVehiclePedIsIn(ped, false)
    local t = GetVehicleClass(car)
  if t == 18 then
    if doeshaverifle == true then

   
      ExecuteCommand('me racks'..config.weapon1name)
      ShowNotification('~g~'..config.weapon1name..' racked')
      doeshaverifle= false
      RemoveWeaponFromPed(ped , config.weapon1)
      

    
    else do
      ShowNotification('"~r~You do not have a '..config.weapon1name..' on you')
      end
  end
  else do
    ShowNotification("~r~ You are not in a vehicle")

  end

  end
else do ShowNotification("~r~This is not a police car")  end


end
    
end)


RegisterCommand('unrack1', function ()


  local ped = GetPlayerPed(-1)
  if IsPedInAnyVehicle(ped, true) then
    local car = GetVehiclePedIsIn(ped, false)
    local t = GetVehicleClass(car)
  if t == 18 then
  if doeshaveshotguh == false then
      
      ExecuteCommand('me unracks '..config.weapon2name..' shotgun')
      ShowNotification('~g~Beanbag '..config.weapon2name..' unracked')

      doeshaveshotguh = true
      GiveWeaponToPed(GetPlayerPed(-1), config.weapon2, 1000, false) 
    
  else do
    ShowNotification('~r~You already have a '..config.weapon2name..' shotgun on you')
  end
end
else do
  ShowNotification("~r~ You are not in a vehicle")
end
end

else do ShowNotification("~r~This is not a police car")  end


end

  
end)

RegisterCommand('rack1', function ()

  local ped = GetPlayerPed(-1)
  if IsPedInAnyVehicle(ped, true) then
    local car = GetVehiclePedIsIn(ped, false)
    local t = GetVehicleClass(car)
  if t == 18 then
    if doeshaveshotguh == true then

      ExecuteCommand('me racks '..config.weapon2name..'')
      ShowNotification('~g~'..config.weapon2name..' racked')
      doeshaveshotguh= false
      RemoveWeaponFromPed(ped , config.weapon2)
      
   
    else do
      ShowNotification("~r~You do not have a '..config.weapon2name..' on you")
      end
  end
  else do
    ShowNotification("~r~You are not in a vehicle")

  end

  end
else do ShowNotification("~r~This is not a police car")  end


end
    
end)

RegisterCommand('loadout', function ()

  local ped = GetPlayerPed(-1)
  RemoveAllPedWeapons(GetPlayerPed(-1), true)
  giveWeapon("weapon_combatpistol")
  weaponComponent("weapon_combatpistol", "COMPONENT_AT_PI_FLSH")
  giveWeapon("weapon_flashlight")
  giveWeapon("weapon_nightstick")
  giveWeapon("weapon_stungun")
  AddArmourToPed(GetPlayerPed(-1), 100)
  ShowNotification("~g~Police loadout has been loaded.")
  ShowNotification('~y~To Use a '..config.weapon1name..' or '..config.weapon2name..', you must type /unrack in a police vehicle.')
end)


function ShowNotification(text)
  SetNotificationTextEntry("STRING")
  AddTextComponentString(text)
  DrawNotification(false, false)
end


function removeWeapon(hash)
  RemoveWeaponFromPed(GetPlayerPed(-1), GetHashKey(hash))
end

function giveWeapon(hash)
  GiveWeaponToPed(GetPlayerPed(-1), GetHashKey(hash), 100, false, true)
end

function weaponComponent(weapon, comp)
  if HasPedGotWeapon(GetPlayerPed(-1), GetHashKey(weapon), false) then
      GiveWeaponComponentToPed(GetPlayerPed(-1), GetHashKey(weapon), GetHashKey(comp))
  end
end








